AUTH_USER = "auth"
FETCH_USERS = "users/fetch"
FETCH_USERS_PAGE2 = "users/fetch_2"
UPDATE_USER = "users/update"
CREATE_USER = "users/create"
CREATE_USER_ERROR = "users/create_error"
DESTROY_USER = "users/destroy"
USER_PROFILES_ASSOCIATION = "users/profiles_association"
USER_BAD_ASSOCIATION = "users/bad_association"

FETCH_DYN_MODELS = "dyn_models/list"
LOAD_DYN_MODEL = "dyn_models/load"

FETCH_ATTRIBUTES = "dyn_models/attributes"
CREATE_ATTRIBUTE = "dyn_models/create_user"