HTTP_AUTH_USER = "http_auth"
HTTP_FETCH_USERS = "users/http_fetch"
HTTP_FETCH_USERS_PAGE2 = "users/http_fetch_2"
HTTP_UPDATE_USER = "users/http_update"
HTTP_CREATE_USER = "users/http_create"
HTTP_CREATE_USER_ERROR = "users/http_create_error"
HTTP_DESTROY_USER = "users/http_destroy"
HTTP_USER_PROFILES_ASSOCIATION = "users/http_profiles_association"
HTTP_USER_BAD_ASSOCIATION = "users/http_bad_association"

DRUBY_AUTH_USER = "druby_auth"
DRUBY_FETCH_USERS = "users/druby_fetch"